export const THEME_EDITOR_PAGES = [
  { key: 'home',     label: 'Home',          path: '/'         },
  { key: 'login',    label: 'Login',         path: '/login'    },
  { key: 'register', label: 'Register',      path: '/register' },
  { key: 'jobs',     label: 'Jobs',          path: '/jobs'     },
  { key: 'global',   label: 'Global / Site', path: null        },
];

export const PREVIEW_WIDTH  = 1280;
export const PREVIEW_HEIGHT = 900;

export const SECTION_LABELS = {
  'home-hero':       'Hero Banner',
  'home-stats':      'Features / Stats',
  'home-about':      'About Section',
  'home-categories': 'Categories',
  'home-guide':      'How It Works',
  'home-cta':        'Call to Action',
  'login-left':      'Left Panel',
  'login-form':      'Sign In Form',
  'register-left':   'Left Panel',
  'register-form':   'Register Form',
  'jobs-hero':       'Page Hero',
  'jobs-empty':      'Empty State',
  'jobs-filters':    'Search & Filters',
  'site-identity':   'Site Identity',
};

export const SECTION_FIELDS = {
  'home-hero': [
    { key: 'tagline',       label: 'Top Label',              type: 'text'     },
    { key: 'title',         label: 'Main Heading',           type: 'textarea' },
    { key: 'subtitle',      label: 'Description',            type: 'textarea' },
    { key: 'bgFrom',        label: 'Gradient Start',         type: 'color'    },
    { key: 'bgTo',          label: 'Gradient End',           type: 'color'    },
    { key: 'btn1Text',      label: 'Primary Button Label',   type: 'text'     },
    { key: 'btn1BgColor',   label: 'Primary Button Color',   type: 'color'    },
    { key: 'btn1TextColor', label: 'Primary Button Text',    type: 'color'    },
    { key: 'btn2Text',      label: 'Secondary Button Label', type: 'text'     },
    { key: 'btn2BgColor',   label: 'Secondary Button Color', type: 'color'    },
    { key: 'btn2TextColor', label: 'Secondary Button Text',  type: 'color'    },
  ],
  'home-stats': [
    { key: 'title',         label: 'Section Heading',          type: 'text'     },
    { key: 'subtitle',      label: 'Section Subtitle',         type: 'text'     },
    { key: 'stat1Value',    label: 'Stat 1 — Value',           type: 'text'     },
    { key: 'stat1Label',    label: 'Stat 1 — Label',           type: 'text'     },
    { key: 'stat2Value',    label: 'Stat 2 — Value',           type: 'text'     },
    { key: 'stat2Label',    label: 'Stat 2 — Label',           type: 'text'     },
    { key: 'stat3Value',    label: 'Stat 3 — Value',           type: 'text'     },
    { key: 'stat3Label',    label: 'Stat 3 — Label',           type: 'text'     },
    { key: 'stat4Value',    label: 'Stat 4 — Value',           type: 'text'     },
    { key: 'stat4Label',    label: 'Stat 4 — Label',           type: 'text'     },
    { key: 'candCardTitle', label: 'Candidates — Card Title',  type: 'text'     },
    { key: 'candCardSub',   label: 'Candidates — Card Subtitle', type: 'text'  },
    { key: 'candCtaText',   label: 'Candidates — CTA Link',    type: 'text'     },
    { key: 'cand1Title',    label: 'Candidate Feature 1 Title',  type: 'text'     },
    { key: 'cand1Desc',     label: 'Candidate Feature 1 Detail', type: 'textarea' },
    { key: 'cand2Title',    label: 'Candidate Feature 2 Title',  type: 'text'     },
    { key: 'cand2Desc',     label: 'Candidate Feature 2 Detail', type: 'textarea' },
    { key: 'cand3Title',    label: 'Candidate Feature 3 Title',  type: 'text'     },
    { key: 'cand3Desc',     label: 'Candidate Feature 3 Detail', type: 'textarea' },
    { key: 'cand4Title',    label: 'Candidate Feature 4 Title',  type: 'text'     },
    { key: 'cand4Desc',     label: 'Candidate Feature 4 Detail', type: 'textarea' },
    { key: 'recCardTitle',  label: 'Recruiters — Card Title',  type: 'text'     },
    { key: 'recCardSub',    label: 'Recruiters — Card Subtitle', type: 'text'   },
    { key: 'recCtaText',    label: 'Recruiters — CTA Link',    type: 'text'     },
    { key: 'rec1Title',     label: 'Recruiter Feature 1 Title',  type: 'text'     },
    { key: 'rec1Desc',      label: 'Recruiter Feature 1 Detail', type: 'textarea' },
    { key: 'rec2Title',     label: 'Recruiter Feature 2 Title',  type: 'text'     },
    { key: 'rec2Desc',      label: 'Recruiter Feature 2 Detail', type: 'textarea' },
    { key: 'rec3Title',     label: 'Recruiter Feature 3 Title',  type: 'text'     },
    { key: 'rec3Desc',      label: 'Recruiter Feature 3 Detail', type: 'textarea' },
    { key: 'rec4Title',     label: 'Recruiter Feature 4 Title',  type: 'text'     },
    { key: 'rec4Desc',      label: 'Recruiter Feature 4 Detail', type: 'textarea' },
  ],
  'home-about': [
    { key: 'title',          label: 'Heading',                   type: 'text'     },
    { key: 'subtitle',       label: 'Subheading',                type: 'textarea' },
    { key: 'body',           label: 'Body Text',                 type: 'textarea' },
    { key: 'ctaText',        label: 'Button Label',              type: 'text'     },
    { key: 'type1Label',     label: 'Job Type 1 — Label',        type: 'text'     },
    { key: 'type1Desc',      label: 'Job Type 1 — Description',  type: 'text'     },
    { key: 'type2Label',     label: 'Job Type 2 — Label',        type: 'text'     },
    { key: 'type2Desc',      label: 'Job Type 2 — Description',  type: 'text'     },
    { key: 'type3Label',     label: 'Job Type 3 — Label',        type: 'text'     },
    { key: 'type3Desc',      label: 'Job Type 3 — Description',  type: 'text'     },
    { key: 'type4Label',     label: 'Job Type 4 — Label',        type: 'text'     },
    { key: 'type4Desc',      label: 'Job Type 4 — Description',  type: 'text'     },
    { key: 'freelanceTitle', label: 'Freelance Panel — Heading', type: 'text'     },
    { key: 'freelanceBody',  label: 'Freelance Panel — Body',    type: 'textarea' },
    { key: 'fl1Mode',        label: 'Freelance Item 1 — Label',  type: 'text'     },
    { key: 'fl1Detail',      label: 'Freelance Item 1 — Detail', type: 'textarea' },
    { key: 'fl2Mode',        label: 'Freelance Item 2 — Label',  type: 'text'     },
    { key: 'fl2Detail',      label: 'Freelance Item 2 — Detail', type: 'textarea' },
    { key: 'fl3Mode',        label: 'Freelance Item 3 — Label',  type: 'text'     },
    { key: 'fl3Detail',      label: 'Freelance Item 3 — Detail', type: 'textarea' },
  ],
  'home-categories': [
    { key: 'title',           label: 'Section Heading',           type: 'text'     },
    { key: 'subtitle',        label: 'Section Subtitle',          type: 'text'     },
    { key: 'allListingsText', label: '"All listings" Link',       type: 'text'     },
    { key: 'remoteDesc',      label: 'Remote — Description',      type: 'textarea' },
    { key: 'hybridDesc',      label: 'Hybrid — Description',      type: 'textarea' },
    { key: 'onsiteDesc',      label: 'On-site — Description',     type: 'textarea' },
    { key: 'freelanceDesc',   label: 'Freelance — Description',   type: 'textarea' },
    { key: 'expHeading',      label: 'Experience Levels Heading', type: 'text'     },
    { key: 'exp1Label',       label: 'Exp Level 1 — Label',       type: 'text'     },
    { key: 'exp1Tag',         label: 'Exp Level 1 — Tag',         type: 'text'     },
    { key: 'exp2Label',       label: 'Exp Level 2 — Label',       type: 'text'     },
    { key: 'exp2Tag',         label: 'Exp Level 2 — Tag',         type: 'text'     },
    { key: 'exp3Label',       label: 'Exp Level 3 — Label',       type: 'text'     },
    { key: 'exp3Tag',         label: 'Exp Level 3 — Tag',         type: 'text'     },
    { key: 'exp4Label',       label: 'Exp Level 4 — Label',       type: 'text'     },
    { key: 'exp4Tag',         label: 'Exp Level 4 — Tag',         type: 'text'     },
  ],
  'home-guide': [
    { key: 'guideTitle',  label: 'Section Title',                type: 'text'     },
    { key: 'guideSub',    label: 'Section Subtitle',             type: 'textarea' },
    { key: 'candLabel',   label: 'Candidate Card — Header',      type: 'text'     },
    { key: 'cand1Title',  label: 'Candidate — Step 1 Title',     type: 'text'     },
    { key: 'cand1Body',   label: 'Candidate — Step 1 Detail',    type: 'textarea' },
    { key: 'cand2Title',  label: 'Candidate — Step 2 Title',     type: 'text'     },
    { key: 'cand2Body',   label: 'Candidate — Step 2 Detail',    type: 'textarea' },
    { key: 'cand3Title',  label: 'Candidate — Step 3 Title',     type: 'text'     },
    { key: 'cand3Body',   label: 'Candidate — Step 3 Detail',    type: 'textarea' },
    { key: 'candCtaText', label: 'Candidate Card — CTA Button',  type: 'text'     },
    { key: 'recLabel',    label: 'Recruiter Card — Header',      type: 'text'     },
    { key: 'rec1Title',   label: 'Recruiter — Step 1 Title',     type: 'text'     },
    { key: 'rec1Body',    label: 'Recruiter — Step 1 Detail',    type: 'textarea' },
    { key: 'rec2Title',   label: 'Recruiter — Step 2 Title',     type: 'text'     },
    { key: 'rec2Body',    label: 'Recruiter — Step 2 Detail',    type: 'textarea' },
    { key: 'rec3Title',   label: 'Recruiter — Step 3 Title',     type: 'text'     },
    { key: 'rec3Body',    label: 'Recruiter — Step 3 Detail',    type: 'textarea' },
    { key: 'recCtaText',  label: 'Recruiter Card — CTA Button',  type: 'text'     },
  ],
  'home-cta': [
    { key: 'title',    label: 'Heading',          type: 'text'     },
    { key: 'subtitle', label: 'Subheading',       type: 'textarea' },
    { key: 'btn1Text', label: 'Primary Button',   type: 'text'     },
    { key: 'btn2Text', label: 'Secondary Button', type: 'text'     },
  ],
  'login-left': [
    { key: 'bgColor', label: 'Background Color', type: 'color'    },
    { key: 'heading', label: 'Main Heading',      type: 'textarea' },
    { key: 'subtext', label: 'Description',       type: 'textarea' },
    { key: 'feat1',   label: 'Feature 1',         type: 'text'     },
    { key: 'feat2',   label: 'Feature 2',         type: 'text'     },
    { key: 'feat3',   label: 'Feature 3',         type: 'text'     },
    { key: 'feat4',   label: 'Feature 4',         type: 'text'     },
    { key: 'feat5',   label: 'Feature 5',         type: 'text'     },
  ],
  'login-form': [
    { key: 'heading',             label: 'Heading',                type: 'text'  },
    { key: 'subheading',          label: 'Subheading',             type: 'text'  },
    { key: 'emailLabel',          label: 'Email Field Label',      type: 'text'  },
    { key: 'emailPlaceholder',    label: 'Email Placeholder',      type: 'text'  },
    { key: 'passwordLabel',       label: 'Password Field Label',   type: 'text'  },
    { key: 'passwordPlaceholder', label: 'Password Placeholder',   type: 'text'  },
    { key: 'noAccountText',       label: '"No account" Text',      type: 'text'  },
    { key: 'createOneText',       label: '"Create one" Link Text', type: 'text'  },
    { key: 'btnText',             label: 'Button Label',           type: 'text'  },
    { key: 'btnBgColor',          label: 'Button Color',           type: 'color' },
    { key: 'btnTextColor',        label: 'Button Text Color',      type: 'color' },
    { key: 'linkColor',           label: 'Link Color',             type: 'color' },
  ],
  'register-left': [
    { key: 'bgColor', label: 'Background Color', type: 'color'    },
    { key: 'heading', label: 'Main Heading',      type: 'textarea' },
    { key: 'subtext', label: 'Description',       type: 'textarea' },
    { key: 'feat1',   label: 'Feature 1',         type: 'text'     },
    { key: 'feat2',   label: 'Feature 2',         type: 'text'     },
    { key: 'feat3',   label: 'Feature 3',         type: 'text'     },
    { key: 'feat4',   label: 'Feature 4',         type: 'text'     },
    { key: 'feat5',   label: 'Feature 5',         type: 'text'     },
  ],
  'register-form': [
    { key: 'step1Label',          label: 'Stepper Step 1 Label',        type: 'text'  },
    { key: 'step2Label',          label: 'Stepper Step 2 Label',        type: 'text'  },
    { key: 'roleStepTitle',       label: 'Role Step — Heading',         type: 'text'  },
    { key: 'roleStepSubtitle',    label: 'Role Step — Subheading',      type: 'text'  },
    { key: 'candRoleTitle',       label: 'Candidate Role — Title',      type: 'text'  },
    { key: 'candRoleDesc',        label: 'Candidate Role — Description', type: 'text' },
    { key: 'recRoleTitle',        label: 'Recruiter Role — Title',      type: 'text'  },
    { key: 'recRoleDesc',         label: 'Recruiter Role — Description', type: 'text' },
    { key: 'backText',            label: 'Back Button Text',            type: 'text'  },
    { key: 'heading',             label: 'Form Heading',                type: 'text'  },
    { key: 'subheading',          label: '"Already have account" Text', type: 'text'  },
    { key: 'ctaText',             label: 'Sign In Link Text',           type: 'text'  },
    { key: 'fullNameLabel',       label: 'Full Name Field Label',       type: 'text'  },
    { key: 'fullNamePlaceholder', label: 'Full Name Placeholder',       type: 'text'  },
    { key: 'emailLabel',          label: 'Email Field Label',           type: 'text'  },
    { key: 'emailPlaceholder',    label: 'Email Placeholder',           type: 'text'  },
    { key: 'passwordLabel',       label: 'Password Field Label',        type: 'text'  },
    { key: 'passwordPlaceholder', label: 'Password Placeholder',        type: 'text'  },
    { key: 'confirmLabel',        label: 'Confirm Password Label',      type: 'text'  },
    { key: 'confirmPlaceholder',  label: 'Confirm Password Placeholder', type: 'text' },
    { key: 'btnText',             label: 'Submit Button Label',         type: 'text'  },
    { key: 'btnBgColor',          label: 'Button Color',                type: 'color' },
    { key: 'btnTextColor',        label: 'Button Text Color',           type: 'color' },
    { key: 'linkColor',           label: 'Link Color',                  type: 'color' },
  ],
  'jobs-hero': [
    { key: 'title',    label: 'Page Title',     type: 'text'     },
    { key: 'subtitle', label: 'Subtitle',       type: 'textarea' },
    { key: 'bgFrom',   label: 'Gradient Start', type: 'color'    },
    { key: 'bgTo',     label: 'Gradient End',   type: 'color'    },
  ],
  'jobs-empty': [
    { key: 'emptyTitle',    label: 'Empty State Heading', type: 'text'     },
    { key: 'emptySubtitle', label: 'Empty State Body',    type: 'textarea' },
  ],
  'jobs-filters': [
    { key: 'pageTitle',         label: 'Page Heading',               type: 'text' },
    { key: 'searchPlaceholder', label: 'Search Placeholder',         type: 'text' },
    { key: 'workModeDefault',   label: '"All work modes" Option',    type: 'text' },
    { key: 'typeDefault',       label: '"All types" Option',         type: 'text' },
    { key: 'clearText',         label: 'Clear Button',               type: 'text' },
    { key: 'prevText',          label: 'Previous Page Button',       type: 'text' },
    { key: 'nextText',          label: 'Next Page Button',           type: 'text' },
    { key: 'applyText',         label: 'Apply Button',               type: 'text' },
    { key: 'messageText',       label: 'Message Button',             type: 'text' },
  ],
  'site-identity': [
    { key: 'siteName',   label: 'Site Name',        type: 'text'     },
    { key: 'tagline',    label: 'Tagline',           type: 'text'     },
    { key: 'nav1Label',  label: 'Nav Link 1 Label',  type: 'text'     },
    { key: 'nav2Label',  label: 'Nav Link 2 Label',  type: 'text'     },
    { key: 'nav3Label',  label: 'Nav Link 3 Label',  type: 'text'     },
    { key: 'navCtaText', label: 'Nav CTA Button',    type: 'text'     },
    { key: 'footerText', label: 'Footer Text',       type: 'textarea' },
    { key: 'copyright',  label: 'Copyright',         type: 'text'     },
  ],
};
