const DEFAULT_THEME_CONFIG = {
  _version: 3,
  colors: {
    primary:    '#2563eb',
    secondary:  '#64748b',
    success:    '#10b981',
    danger:     '#ef4444',
    warning:    '#f59e0b',
    background: '#ffffff',
    surface:    '#f9fafb',
    text:       '#111827',
    textMuted:  '#6b7280',
    border:     '#e5e7eb',
  },
  fonts: {
    primary: 'Inter, system-ui, sans-serif',
  },
  pages: {
    home: {
      label: 'Home Page',
      path:  '/',
      sections: [
        {
          id: 'home-hero', type: 'home-hero', order: 0, visible: true,
          settings: {
            tagline:       'Jobs & freelance work in one place',
            title:         'Find work.\nHire talent.',
            subtitle:      'Browse job listings, apply with one click, post roles, and manage applicants or freelancers — from the same account.',
            bgFrom:        '',
            bgTo:          '',
            btn1Text:      'Browse Jobs',
            btn1BgColor:   '',
            btn1TextColor: '',
            btn2Text:      'Create Account',
            btn2BgColor:   '',
            btn2TextColor: '',
          },
        },
        {
          id: 'home-stats', type: 'home-stats', order: 1, visible: true,
          settings: {
            title:         'Built for candidates. Built for recruiters.',
            subtitle:      "Everything you need on whichever side of hiring you're on.",
            stat1Value:    '', stat1Label: 'Jobs Posted',
            stat2Value:    '', stat2Label: 'Companies',
            stat3Value:    '', stat3Label: 'Candidates',
            stat4Value:    '', stat4Label: 'Placements Made',
            candCardTitle: 'For Candidates',
            candCardSub:   'Looking for your next role',
            candCtaText:   'Sign up free →',
            recCardTitle:  'For Recruiters',
            recCardSub:    'Building your team',
            recCtaText:    'Start posting →',
            cand1Title:    'One profile, every job',
            cand1Desc:     'Upload your CV, list your skills and experience, and apply to any listing in one click — your profile does the talking.',
            cand2Title:    'Filter by what matters',
            cand2Desc:     'Sort by job type, work mode (remote, hybrid, on-site), salary, experience level, or category.',
            cand3Title:    'Save & track applications',
            cand3Desc:     "Bookmark roles you're eyeing. See the status of every application you've submitted in one dashboard.",
            cand4Title:    'Freelance mode',
            cand4Desc:     'Toggle on freelance availability. Submit bids on project-based roles or accept direct invitations from recruiters.',
            rec1Title:     'Post full-time or freelance roles',
            rec1Desc:      'Create listings for employment and project-based work. Set budgets, hiring mode, and visibility in minutes.',
            rec2Title:     'Two ways to hire freelancers',
            rec2Desc:      'Open your role to public bids, or search and invite specific freelancers directly — or do both.',
            rec3Title:     'Manage applicants & schedule interviews',
            rec3Desc:      'Review applications, update statuses, and schedule interview times straight from your dashboard.',
            rec4Title:     'Contracts & billing',
            rec4Desc:      'Accepted bids and invitations become tracked contracts. Subscription plans control how many roles you can post.',
          },
        },
        {
          id: 'home-about', type: 'home-about', order: 2, visible: true,
          settings: {
            title:          'Full-time, part-time,\nfreelance — all here.',
            subtitle:       '',
            body:           'HireWire handles traditional employment and freelance hiring under one roof. Post a full-time role and a project contract at the same time — from the same dashboard.\n\nCandidates can also switch on freelance mode to make themselves discoverable for project work, without giving up their regular job search.',
            ctaText:        'Browse open roles',
            type1Label:     'Full-time',
            type1Desc:      'Permanent employment roles',
            type2Label:     'Part-time',
            type2Desc:      'Flexible hour positions',
            type3Label:     'Internship',
            type3Desc:      'Student & graduate placements',
            type4Label:     'Freelance',
            type4Desc:      'Project-based contract work',
            freelanceTitle: 'Two ways to find freelancers.',
            freelanceBody:  'Open your freelance role to public bids — freelancers apply with their price and timeline. Or search the pool and send direct invitations to people whose profiles match what you need. Or both.',
            fl1Mode:        'Public bids',
            fl1Detail:      'Post a role. Freelancers submit their price, delivery time, and pitch. You review and accept.',
            fl2Mode:        'Direct invitations',
            fl2Detail:      'Search freelancers by skill and location. Invite the ones you want. They accept or decline.',
            fl3Mode:        'Contracts',
            fl3Detail:      'Every accepted bid or invitation becomes a tracked contract — status, price, and chat included.',
          },
        },
        {
          id: 'home-categories', type: 'home-categories', order: 3, visible: true,
          settings: {
            title:           'How do you want to work?',
            subtitle:        'Filter by work mode when you browse.',
            remoteDesc:      'Work from anywhere. Filter by remote-only listings across all job types.',
            hybridDesc:      'Split your week. Office time with flexibility built in.',
            onsiteDesc:      'In-person, full-time presence. Search roles at physical locations.',
            freelanceDesc:   'Project-based work. Set your own price and timeline.',
            exp1Label:       'Entry Level',
            exp1Tag:         'No experience required',
            exp2Label:       'Mid Level',
            exp2Tag:         '2–5 years',
            exp3Label:       'Senior',
            exp3Tag:         '5+ years',
            exp4Label:       'Internship',
            exp4Tag:         'Students & graduates',
            expHeading:      'Browse by experience level',
            allListingsText: 'All listings →',
          },
        },
        {
          id: 'home-guide', type: 'home-guide', order: 4, visible: true,
          settings: {
            guideTitle:  'From zero to hired.',
            guideSub:    "Here's exactly how it works — no surprises, no fine print.",
            cand1Title:  'Create your profile',
            cand1Body:   'Add your skills, experience, education, and upload your CV. Recruiters search by all of this.',
            cand2Title:  'Browse & filter jobs',
            cand2Body:   'Filter by type, work mode, salary, experience level, and location. Save the ones worth coming back to.',
            cand3Title:  'Apply in one click',
            cand3Body:   'Your profile is your application. Track every submission from your personal dashboard.',
            rec1Title:   'Set up your company',
            rec1Body:    'Add your company name, logo, and details. Takes two minutes.',
            rec2Title:   'Post your role',
            rec2Body:    'Choose employment type, work mode, salary range, and requirements. Standard job or freelance project — your call.',
            rec3Title:   'Review & hire',
            rec3Body:    'Manage applicants, schedule interviews, review bids, or invite freelancers directly. Accepted hires become tracked contracts.',
            candLabel:   'As a candidate',
            recLabel:    'As a recruiter',
            candCtaText: 'Create candidate account →',
            recCtaText:  'Create recruiter account →',
          },
        },
        {
          id: 'home-cta', type: 'home-cta', order: 5, visible: true,
          settings: {
            title:    'Your next hire — or your next job — starts here.',
            subtitle: 'Free to sign up. No credit card required to browse listings or build your profile.',
            btn1Text: 'Get started',
            btn2Text: 'Browse jobs first',
          },
        },
      ],
    },

    login: {
      label: 'Login Page',
      path:  '/login',
      sections: [
        {
          id: 'login-left', type: 'login-left', order: 0, visible: true,
          settings: {
            bgColor: '#2B3FE7',
            heading: 'Find work.\nHire better.\nAll in one place.',
            subtext: 'Browse listings, apply with one click, post roles, and manage your entire hiring pipeline — all from a single account.',
            feat1:   'Free account forever',
            feat2:   'One-click job applications',
            feat3:   'Real-time pipeline tracking',
            feat4:   'Integrated messaging',
            feat5:   'Freelance bidding system',
          },
        },
        {
          id: 'login-form', type: 'login-form', order: 1, visible: true,
          settings: {
            heading:             'Welcome back',
            subheading:          'Sign in to your account',
            emailLabel:          'Email Address',
            emailPlaceholder:    'you@example.com',
            passwordLabel:       'Password',
            passwordPlaceholder: 'Your password',
            noAccountText:       "Don't have an account?",
            createOneText:       'Create one',
            btnText:             'Sign In',
            btnBgColor:          '#2563eb',
            btnTextColor:        '#ffffff',
            linkColor:           '#2563eb',
          },
        },
      ],
    },

    register: {
      label: 'Register Page',
      path:  '/register',
      sections: [
        {
          id: 'register-left', type: 'register-left', order: 0, visible: true,
          settings: {
            bgColor: '#2B3FE7',
            heading: 'Find work.\nHire better.\nAll in one place.',
            subtext: 'Browse listings, apply with one click, post roles, and manage your entire hiring pipeline — all from a single account.',
            feat1:   'Free account forever',
            feat2:   'One-click job applications',
            feat3:   'Real-time pipeline tracking',
            feat4:   'Integrated messaging',
            feat5:   'Freelance bidding system',
          },
        },
        {
          id: 'register-form', type: 'register-form', order: 1, visible: true,
          settings: {
            step1Label:          'Choose Role',
            step2Label:          'Create Account',
            roleStepTitle:       'I am a...',
            roleStepSubtitle:    'Choose your role to get started',
            candRoleTitle:       'Job Seeker / Freelancer',
            candRoleDesc:        'Find jobs, bid on projects, track applications',
            recRoleTitle:        'Recruiter / Employer',
            recRoleDesc:         'Post jobs, manage pipeline, hire top talent',
            backText:            '← Back',
            heading:             'Create an account',
            subheading:          'Already have an account?',
            ctaText:             'Sign in',
            fullNameLabel:       'Full Name',
            fullNamePlaceholder: 'Your full name',
            emailLabel:          'Email Address',
            emailPlaceholder:    'you@example.com',
            passwordLabel:       'Password',
            passwordPlaceholder: 'Min. 6 characters',
            confirmLabel:        'Confirm Password',
            confirmPlaceholder:  'Repeat password',
            btnText:             'Create account',
            btnBgColor:          '#2563eb',
            btnTextColor:        '#ffffff',
            linkColor:           '#2563eb',
          },
        },
      ],
    },

    jobs: {
      label: 'Jobs Page',
      path:  '/jobs',
      sections: [
        {
          id: 'jobs-hero', type: 'jobs-hero', order: 0, visible: false,
          settings: {
            title:    'Find Your Next Opportunity',
            subtitle: 'Browse hundreds of roles across every industry. Filter by location, type, and skill — apply in seconds.',
            bgFrom:   '#2563eb',
            bgTo:     '#4f46e5',
          },
        },
        {
          id: 'jobs-empty', type: 'jobs-empty', order: 1, visible: true,
          settings: {
            emptyTitle:    'No jobs found',
            emptySubtitle: 'Try adjusting your search or clearing your filters.',
          },
        },
        {
          id: 'jobs-filters', type: 'jobs-filters', order: 2, visible: true,
          settings: {
            pageTitle:         'Find Jobs',
            searchPlaceholder: 'Search by title or company...',
            workModeDefault:   'All work modes',
            typeDefault:       'All types',
            clearText:         'Clear',
            prevText:          '← Previous',
            nextText:          'Next →',
            applyText:         'Apply',
            messageText:       'Message',
          },
        },
      ],
    },

    global: {
      label: 'Global / Site',
      path:  null,
      sections: [
        {
          id: 'site-identity', type: 'site-identity', order: 0, visible: true,
          settings: {
            siteName:   '',
            tagline:    'Jobs & freelance in one place',
            nav1Label:  'Home',
            nav2Label:  'Browse Jobs',
            nav3Label:  'Contact',
            navCtaText: 'Post a Job',
            footerText: 'Connecting talent with opportunity.',
            copyright:  '© 2025 HireWire. All rights reserved.',
          },
        },
      ],
    },
  },
};

module.exports = { DEFAULT_THEME_CONFIG };
